name: Promote Model to Production

on:
  workflow_dispatch:  # Ручной запуск или триггер из другого workflow
  repository_dispatch:
    types: [promote-to-prod]

jobs:
  promote-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow boto3

      - name: Promote to Production
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python -c "
          from mlflow.tracking import MlflowClient
          mlflow.set_tracking_uri("http://localhost:5000")
          client = MlflowClient()
          
          # Найти staging-версию модели
          staging_version = client.get_latest_versions('IrisClassifier', stages=['Staging'])[0]
          
          # Перевести staging-версию в Production
          client.transition_model_version_stage(
              name='IrisClassifier',
              version=staging_version.version,
              stage='Production',
              archive_existing_versions=True  # Автоматически архивирует старую production-версию
          )
          print(f'Model {staging_version.version} promoted to Production')
          "